### ISSUE TITLE
Does not handle when websocket is already closed

### ISSUE THREAD

**Issue by gemmell** [luzzif/websocket-heartbeats#2]
Looks like it's not checking whether it's already closed before calling ping?
`Error: not opened
    at WebSocket.ping (/home/ubuntu/trading/bigdipper2/node_modules/ws/lib/WebSocket.js:313:13)
    at Timeout.setInterval [as _onTimeout] (websocket-heartbeats/src/main/HeartbeatHandler.ts:83:28)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
`

**Comment by gemmell** [comment]
PR: https://github.com/luzzif/websocket-heartbeats/pull/3

**Comment by luzzif** [comment]
Thanks for the hint, the problem should be fixed in 1.2.0.
